apiVersion: v1
appVersion: "1.0"
description: eTools Helm Chart
home: https://etools.unicef.org
name: etools
version: 0.1.0
maintainers:
  - name: Robert Avram
    email: ravram@unicef.org
appversion: 8.0.0