apiVersion: v1
kind: Service
metadata:
  annotations:
  name: etwebservice-pmp
spec:
  ports:
  - name: 80tcp01
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ include "name" . }}
  type: NodePort