{% raw %}apiVersion: v1
kind: Service
metadata:
  annotations:
  name: {{ include "name" .}}-service{% endraw %}
spec:
  ports:
  - name: 80tcp01
    port: 8080
    protocol: TCP
    targetPort: {{cookiecutter.container_port}}
{% raw %}
  selector:
    app: {{ include "name" . }}
  type: NodePort
{% endraw %}