apiVersion: v1
kind: Service
metadata:
  annotations:
  name: etservice-web
spec:
  ports:
  - name: 80tcp01
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ include "name" . }}-web
  type: NodePort